### ISSUE TITLE
`DataFrame` constructor from a `Vector` of vectors requires passing :auto

### ISSUE THREAD

**Issue by feanor12** [JuliaAPlavin/FlexiJoins.jl#9] opened 2024-06-03 13:06 UTC
groupby does not work with DataFrames.
This might be related to the constructor change in DataFrames

```julia
julia> versioninfo()
Julia Version 1.10.3
Commit 0b4590a550 (2024-04-30 10:59 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)

julia> Pkg.status()
Status `C:\Users\pusterhofer\AppData\Local\Temp\jl_kGUvNH\Project.toml`
  [6e4b80f9] BenchmarkTools v1.5.0
  [02685ad9] DataPipes v0.3.16
  [e37f2e79] FlexiJoins v0.1.33
⌅ [8197267c] IntervalSets v0.7.7
  [09ab397b] StructArrays v0.6.18
  [a93c6f00] DataFrames v1.6.1
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated`
```

```julia
julia> df = DataFrame([1:5,2:6],:auto)
5×2 DataFrame
 Row │ x1     x2
     │ Int64  Int64
─────┼──────────────
   1 │     1      2
   2 │     2      3
   3 │     3      4
   4 │     4      5
   5 │     5      6

julia> leftjoin((df,df),by_pred(x->1..(x.x1),∋,:x1),groupby=1)
ERROR: ArgumentError: `DataFrame` constructor from a `Vector` of vectors requires passing :auto as a second argument to automatically generate column names: `DataFrame(vecs, :auto)`
Stacktrace:
 [1] DataFrame(vecs::Vector{StructVector{@NamedTuple{…}, @NamedTuple{…}, CartesianIndex{…}}})
   @ DataFrames C:\Users\pusterhofer\.julia\packages\DataFrames\58MUJ\src\dataframe\dataframe.jl:405
 [2] to_df_joined(xs::Vector{StructVector{@NamedTuple{…}, @NamedTuple{…}, CartesianIndex{…}}})
   @ DataFramesExt C:\Users\pusterhofer\.julia\packages\FlexiJoins\EQwK4\ext\DataFramesExt.jl:16
 [3] map(f::typeof(DataFramesExt.to_df_joined), t::Tuple{StructVector{…}, Vector{…}})
   @ Base .\tuple.jl:292
 [4] _flexijoin(datas::Tuple{…}, args::FlexiJoins.ByPred{…}; kwargs::@Kwargs{…})
   @ DataFramesExt C:\Users\pusterhofer\.julia\packages\FlexiJoins\EQwK4\ext\DataFramesExt.jl:12
 [5] _flexijoin
   @ C:\Users\pusterhofer\.julia\packages\FlexiJoins\EQwK4\ext\DataFramesExt.jl:9 [inlined]
 [6] flexijoin
   @ C:\Users\pusterhofer\.julia\packages\FlexiJoins\EQwK4\src\joins.jl:27 [inlined]
 [7] #leftjoin#109
   @ C:\Users\pusterhofer\.julia\packages\FlexiJoins\EQwK4\src\joins.jl:13 [inlined]
 [8] top-level scope
   @ REPL[148]:1
Some type information was truncated. Use `show(err)` to see complete types.

julia> leftjoin((df,df),by_pred(x->1..(x.x1),∋,:x1))
15×4 DataFrame
 Row │ x1     x2     x1_1   x2_1
     │ Int64  Int64  Int64  Int64
─────┼────────────────────────────
   1 │     1      2      1      2
   2 │     2      3      1      2
   3 │     2      3      2      3
   4 │     3      4      1      2
   5 │     3      4      2      3
   6 │     3      4      3      4
   7 │     4      5      1      2
   8 │     4      5      2      3
   9 │     4      5      3      4
  10 │     4      5      4      5
  11 │     5      6      1      2
  12 │     5      6      2      3
  13 │     5      6      3      4
  14 │     5      6      4      5
  15 │     5      6      5      6

```

**Comment by aplavin** [comment] 2024-06-03 13:42
Yeah I don’t think FlexiJoins grouping ever worked with dataframes… Overall, dataframes support here is pretty basic as I never really use them myself, preferring basic tables with Julian interface (vectors, structarrays).

Feel free to make a PR adding grouping support for DFs!
The current df support was added solely because someone requested it and implementation turned out to be very simple – https://github.com/JuliaAPlavin/FlexiJoins.jl/blob/master/ext/DataFramesExt.jl. Grouping is probably more involved, not sure if I'll find time to implement it, and not familiar with dataframes anyway.

**Comment by aplavin** [comment] 2024-10-15 01:26
The original example never worked, so it's not a regression.

Closing this issue for now, as I don't have any plans to work on it. I don't use DataFrames myself and don't have that expertise – PRs to improve that are welcome!

**Closed as completed by aplavin** 2024-10-15 01:26 UTC
